#cloud-config

write_files:
  - path: "/home/start.sh"
    permissions: "0755"
    content: |
      #!/bin/bash

      apt-get install aufs-tools
      chmod +x -R /usr/local/bin
      docker daemon >"/tmp/docker.log" 2>&1 &

      sleep 5

      docker network create --subnet=172.18.0.0/16 test

      kubelet --allow-privileged \
        --v=5 \
        --chaos-chance=0.0 \
        --container-runtime="docker" \
        --address="0.0.0.0" \
        --api-servers="${MASTER_IP}:${MASTER_PORT}" \
        --cpu-cfs-quota=false \
        --port=10250 \
        --cluster-dns=8.8.8.8 \
        --pod_infra_container_image="kubernetes/pause" \
        >"/tmp/kubelet.log" 2>&1 &

      kube-proxy \
        --v=5 \
        --master="http://${MASTER_IP}:${MASTER_PORT}" \
        >/dev/null 2>/dev/null &
